# Generated by Selenium IDE
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestTest(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.get("https://192.168.1.51:8443/")
        self.vars = {}

    def test_test(self):
        self.driver.set_window_size(1920, 1040)
        self.driver.find_element(By.ID, "login_img").click()
        time.sleep(1)
        self.driver.find_element(By.NAME, "name").click()
        time.sleep(1)
        self.driver.find_element(By.NAME, "name").send_keys("systemadmin")
        time.sleep(1)
        # self.driver.find_element(By.ID, "myForm").click()
        self.driver.find_element(By.NAME, "pass").click()
        self.driver.find_element(By.NAME, "pass").send_keys("12345678")
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > img").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.CSS_SELECTOR, "#outlookdivin0 > span:nth-child(1) td").click()
        self.driver.find_element(By.LINK_TEXT, "用户管理").click()
        self.driver.switch_to.default_content()
        self.driver.switch_to.frame(6)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.ID, "userId").click()
        self.driver.find_element(By.ID, "userId").send_keys("cs")
        self.driver.find_element(By.ID, "search").click()
        self.driver.switch_to.default_content()
        self.driver.switch_to.default_content()
        self.driver.switch_to.frame(5)
        self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(4) span:nth-child(1)").click()
        self.driver.close()

    def tearDown(self):
        self.driver.quit()


if __name__ == '__main__':
    unittest.main()
